version: "3"

services:
  backend:
    build: ./
    container_name: music_container
    working_dir: /music
    command:
      - ./commands/start_server.sh
    ports:
      - 8010:8000
    volumes:
      - ./src:/music/src
      - ./commands:/music/commands
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: { }
