# Generated by Django 4.1.6 on 2023-02-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="media/img/profiles"),
        ),
    ]
