# Generated by Django 4.1.6 on 2023-02-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_customer_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
