# Generated by Django 4.1.6 on 2023-03-07 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_customer_birth_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(choices=[("Male", "Male"), ("Female", "Female")], max_length=6),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("User", "User"), ("Musician", "Musician")],
                        max_length=10,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="user_profile_photo/"),
                ),
                (
                    "favourite_genres",
                    models.CharField(
                        choices=[
                            ("Rock", "Rock"),
                            ("Pop", "Pop"),
                            ("Hip Hop", "Hip Hop"),
                            ("Jazz", "Jazz"),
                            ("Blues", "Blues"),
                            ("Classical", "Classical"),
                            ("Electronic", "Electronic"),
                            ("Folk", "Folk"),
                            ("Reggae", "Reggae"),
                            ("Metal", "Metal"),
                            ("R&B", "R&B"),
                            ("Soul", "Soul"),
                            ("Funk", "Funk"),
                        ],
                        max_length=30,
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("city", models.CharField(max_length=200, null=True)),
                ("postcode", models.CharField(max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
