# Generated by Django 4.1.6 on 2023-03-13 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_userprofile_favourite_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="photo",
        ),
    ]
