# Generated by Django 4.1.6 on 2023-02-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0002_album_create_datetime_album_last_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genres",
                to="music.genre",
            ),
        ),
    ]
