# Generated by Django 4.1.6 on 2023-02-17 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0004_alter_album_genre_alter_track_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genres",
                to="music.genre",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="music.album",
            ),
        ),
    ]
