# Generated by Django 4.1.6 on 2023-02-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0005_alter_album_genre_alter_track_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="artist",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="track",
            name="create_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="track_file",
            field=models.FileField(blank=True, upload_to="tracks/"),
        ),
    ]
