# Generated by Django 4.1.6 on 2023-02-20 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_alter_track_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_datetime", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_update", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("biography", models.TextField(default="biography", null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="playlist",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="track",
            options={"ordering": ["title"]},
        ),
        migrations.RenameField(
            model_name="album",
            old_name="album_title",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="genre_title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="playlist",
            old_name="playlist_title",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="album",
            name="text",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="track",
        ),
        migrations.AddField(
            model_name="album",
            name="description",
            field=models.TextField(default="description", null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="tracks",
            field=models.ManyToManyField(related_name="playlist_tracks", to="music.track"),
        ),
        migrations.AlterField(
            model_name="track",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist",
                to="music.artist",
            ),
        ),
    ]
