# Generated by Django 4.1.6 on 2023-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0009_favoritetrack"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="play_count",
            field=models.IntegerField(default=0),
        ),
    ]
