# Generated by Django 4.1.6 on 2023-03-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0010_track_play_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="image",
            field=models.ImageField(default="default.png", upload_to="covers/"),
        ),
    ]
