# Generated by Django 4.1.6 on 2023-04-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0014_alter_track_album_alter_track_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="music.album",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist",
                to="music.artist",
            ),
        ),
    ]
