# Generated by Django 4.1.6 on 2023-04-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0015_alter_track_album_alter_track_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="title",
            field=models.CharField(default="Playlist", max_length=200),
        ),
        migrations.AlterField(
            model_name="track",
            name="track_file",
            field=models.FileField(upload_to="tracks/"),
        ),
    ]
