# Generated by Django 4.1.6 on 2023-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0016_alter_playlist_title_alter_track_track_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
    ]
