# Generated by Django 4.1.6 on 2023-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0017_alter_album_description_alter_artist_biography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
    ]
